### ISSUE TITLE
Error. No sidebar transition

### ISSUE THREAD

**Issue by kalverra** [pato13/f1-3-c2p1-colmar-academy#3]
https://github.com/pato13/f1-3-c2p1-colmar-academy/blob/master/capstone/index.html#L87

Like your nav, it seems your sidebar has issues converting when the page gets smaller. Review your media queries. https://developer.mozilla.org/en-US/docs/Web/CSS/Media_Queries/Using_media_queries

**Comment by pato13** [comment]
thanks
